import type { Metadata } from 'next'

import './globals.css'
import { Sidebar } from '@/src/widgets/home/ui/Sidebar'
import { inter } from '@/app/fonts'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'NBhey-frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="ru" className={`${inter.className} h-full antialiased`}>
      <body className="p-1 md:flex flex-col flex-1 items-center justify-center min-h-full max-h-157.5 bg-background ">
        <div className="p-4 relative max-w-300 w-full md:h-150 flex flex-col md:flex-row md:border border-[#C7C4D7] rounded-lg">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
