import type { Metadata } from 'next'

import './globals.css'
import { Sidebar } from '@/src/widgets/home/ui/Sidebar'
import { inter } from '@/app/fonts'

export const metadata: Metadata = {
  title: 'NBhey-frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru" className={`${inter.className} h-full antialiased`}>
      <body className="flex flex-col flex-1 items-center justify-center min-h-full bg-background">
        <div className="realtive max-w-300 w-full h-auto min-h-140 flex items-center border border-[#C7C4D7] rounded-lg">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  )
}
